### PR TITLE
8 to 9 20210104

### PR DESCRIPTION
**Pull request by nkoenig**
This merges transport8 to transport9, which is just topic statistics.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
LGTM

**Review by chapulina — CHANGES_REQUESTED** [review]
We should require `ign-msgs 6.2` on `CMakeLists`.

I'm not sure why the Windows CI is not finding the statistics message.

**Comment by nkoenig** [comment]
> We should require `ign-msgs 6.2` on `CMakeLists`.
Done in edccca4df40dbaed94da6db26f367bb1898e9e1f

**Review by chapulina — APPROVED** [review]

**Comment by chapulina** [comment]
> I'm not sure why the Windows CI is not finding the statistics message.

It looks like CI is using an old branch:

`Installing branch master of ign-msgs`

**Pull request merged**
