### PR TITLE
 Make zmq check for post 4.3.1 not to include 4.3.1

### PR DESCRIPTION
**Pull request by j-rivero**
# 🦟 Bug fix

## Summary

When building Debian packages for Debian/Buster I needed to use this patch to fix compilation. Seems like we were including the `4.3.1` to define the `IGN_ZMQ_POST_4_3_1` variable, which clearly seems to be a mistake.

## Checklist
- [x] Signed all commits for DCO

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by caguero** [comment]
CC @mjcarroll . I remember he created a PR to fix a problem in Debian because the version of the code they had didn't make a lot of sense. Just double checking...

**Comment by mjcarroll** [comment]
Here was the original context: https://github.com/ignitionrobotics/ign-transport/issues/157 and the original fix: https://github.com/ignitionrobotics/ign-transport/pull/159

**Comment by chapulina** [comment]
Thanks for the context, @mjcarroll . The original issue was failing the Focal build, but this PR passes on Focal. So I think there's no regression here.

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-10/1228/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-25-fortress-edifice-citadel/1343/1

**Pull request merged**
