### PR TITLE
Use private access modifier for pImpl variable in MsgIter class

### PR DESCRIPTION
**Pull request by adlarkin**
It looks like we accidentally had a pImpl variable for a class be set to `public`. This changes the access to `private`.

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
LGTM, ok to merge during beta since it's a bug fix.

**Comment by adlarkin** [comment]
> LGTM, ok to merge during beta since it's a bug fix.

Any idea why CI failed for Focal, but not for Bionic?

**Comment by chapulina** [comment]
> Any idea why CI failed for Focal, but not for Bionic?

It failed when uploading the coverage report to codecov. I've been removing the `CODECOV_TOKEN` from the Focal builds to help with that, because we only need the coverage report uploaded once. Feel free to remove these 2 lines in this PR:

https://github.com/ignitionrobotics/ign-transport/blob/47fb69bdeb95beeedd3bd2724e0de9f7ca23c45b/.github/workflows/ci.yml#L26-L27

**Review by chapulina — APPROVED** [review]

**Comment by adlarkin** [comment]
Should we merge this PR, or do we need to wait for @caguero to give the green light?

**Comment by caguero** [comment]
> Should we merge this PR, or do we need to wait for @caguero to give the green light?

No need to wait for me if there are approvals unless there's a complex change or very important design decision. Feel free to merge!

**Pull request merged**
