### PR TITLE
Use libexec to install lib binaries

### PR DESCRIPTION
**Pull request by j-rivero**
We are installing the cli11 binaries in under the standard library path which is something that does not fit well according to the [FHR](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec). libexec seems a better place for them:

```
4.7.1. Purpose

/usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.
```

### CODE REVIEW

**Review by caguero — APPROVED** [review]

**Comment by chapulina** [comment]
Do we need any changes to the `-release` repo?

**Comment by j-rivero** [comment]
> Do we need any changes to the `-release` repo?

Yes! https://github.com/ignition-release/ign-transport11-release/pull/4

**Comment by mjcarroll** [comment]
The CLI binaries can still be executed standalone by a user if they don't wish to use `ign`, so I don't know if `libexec` is the correct location for them.

**Comment by chapulina** [comment]
@mjcarroll has a good point. Maybe we need to create new `ignition-transport11` packages for the binaries?

**Comment by chapulina** [comment]
> Maybe we need to create new ignition-transport11 packages for the binaries?

I believe this is what's being suggested for `plugin2` here, right @j-rivero ?

* https://github.com/ignition-release/ign-plugin2-release/pull/5

**Comment by j-rivero** [comment]
> 

Yep, the same.

**Review by mjcarroll — APPROVED** [review]

**Comment by j-rivero** [comment]
Updated the -release repo PR https://github.com/ignition-release/ign-transport11-release/pull/4

**Pull request merged**
