### PR TITLE
9 to 10 20210104

### PR DESCRIPTION
**Pull request by nkoenig**
Requires https://github.com/ignitionrobotics/ign-msgs/pull/123

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
There shouldn't be an `ign-transport10` branch yet. That's the current version under development. Version 10 is currently on `main` (which used to be `default` on BitBucket)

**Comment by caguero** [comment]
There's a conflict in `src/NodeShared.cc`.

**Comment by caguero** [comment]
> There's a conflict in `src/NodeShared.cc`.

Fixed in 2273d63.

**Review by chapulina — CHANGES_REQUESTED** [review]
There seems to be 2 things combined in this PR. The merge from 9, and the bump of `ign-msgs` to version 7. I think if it was just the merge, it would probably be good to merge. But the bump in dependency still needs updates on CI.

**Comment by nkoenig** [comment]
> There seems to be 2 things combined in this PR. The merge from 9, and the bump of `ign-msgs` to version 7. I think if it was just the merge, it would probably be good to merge. But the bump in dependency still needs updates on CI.

Right, we need to make an ign-msgs7 prerelease.

**Comment by chapulina** [comment]
homebrew CI needs https://github.com/osrf/homebrew-simulation/pull/1293

**Review by chapulina — APPROVED** [review]

**Pull request merged**
