### PR TITLE
7 to 8

### PR DESCRIPTION
**Pull request by adlarkin**
Forward-port [ign-transport7](https://github.com/ignitionrobotics/ign-transport/tree/ign-transport7) to [ign-transport8](https://github.com/ignitionrobotics/ign-transport/tree/ign-transport8). The comparison between these branches can be found [here](https://github.com/ignitionrobotics/ign-transport/compare/ign-transport8...ign-transport7).

### CODE REVIEW

**Comment by adlarkin** [comment]
It looks like DCO is failing, but I think it's a false negative. Here is the message from DCO:

> Commit sha: 664e0d2, Author: Carlos Agüero, Committer: GitHub; Expected "Carlos Agüero caguero@osrfoundation.org", but got "Carlos Agüero caguero@openrobotics.org".

**Review by chapulina — APPROVED** [review]
> It looks like DCO is failing, but I think it's a false negative. 

Yeah it looks like @caguero 's email is `osfroundation` somewhere and `openrobotics` somewhere else, causing a discrepancy. I manually approved for now.

---

I see that this PR is showing no file diffs. I believe this is happening because #176 was already forward-ported on #177, but #177 was squashed / rebased, which causes branch `ign-transport8` not to know that it has the commit from #176. That's why we need to remember to create a merge commit when forward-porting.

In any case, I think it's good to get this PR in so that the [branch comparison](https://github.com/ignitionrobotics/ign-transport/compare/ign-transport8...ign-transport7) can be cleared.

**Review by caguero — COMMENTED** [review]
I thought I forward ported these changes in https://github.com/ignitionrobotics/ign-transport/pull/177. Is this PR needed? I see an empty diff as well.

**Comment by adlarkin** [comment]
> I thought I forward ported these changes in #177. Is this PR needed? I see an empty diff as well.

@caguero @chapulina it's up to you guys regarding whether we should merge this or not. I created this originally because the branch comparison showed a difference, but you're right, this PR has no diff. If we think it would be good to clear the branch comparison, we can merge it, but I wonder if that would create a bit of confusion in the history since we already merged #177.

**Comment by chapulina** [comment]
> Is this PR needed?

@caguero , I think you either squash-merged or rebase-merged #177. Using these strategies changes the commit hash, so git doesn't know that the specific PR #176 is part of `ign-transport8`: https://github.com/ignitionrobotics/ign-transport/compare/ign-transport8...ign-transport7

I think it's good to get this PR in, so we have a clear diff between the branches. Code-wise, it won't make a difference.

**Comment by caguero** [comment]
> > Is this PR needed?
> 
> @caguero , I think you either squash-merged or rebase-merged #177. Using these strategies changes the commit hash, so git doesn't know that the specific PR #176 is part of `ign-transport8`: [ign-transport8...ign-transport7](https://github.com/ignitionrobotics/ign-transport/compare/ign-transport8...ign-transport7)
> 
> I think it's good to get this PR in, so we have a clear diff between the branches. Code-wise, it won't make a difference.

I see, probably I hit the wrong merge strategy. Looks good to me, then.

**Review by caguero — APPROVED** [review]

**Comment by chapulina** [comment]
@adlarkin , feel free to merge using "Create a merge commit". Be sure to add your signature to the commit text.

**Pull request merged**
