### PR TITLE
One NodeShared per process

### PR DESCRIPTION
**Pull request by joxoby**
This PR tries to address: https://github.com/ignitionrobotics/ign-transport/issues/137

### CODE REVIEW

**Comment by caguero** [comment]
@osrf-jenkins run tests please

**Comment by joxoby** [comment]
@caguero is test `TEST(twoProcPubSub, SubThrottled)` during check `ignition_transport-ci-pr_any-homebrew-amd64` known to fail?

**Comment by caguero** [comment]
> @caguero is test `TEST(twoProcPubSub, SubThrottled)` during check `ignition_transport-ci-pr_any-homebrew-amd64` known to fail?

Yes, it's flaky test on Homebrew.

**Review by caguero — APPROVED** [review]
Looks good to me. I like the use of `std::shared_mutex` to optimize the most common operation.

Thanks!

**Pull request merged**
