### PR TITLE
 7 ➡️ 8 

### PR DESCRIPTION
**Pull request by chapulina**
I'm not sure about some of the changes, please review with care, @caguero :wink:

### CODE REVIEW

**Comment by chapulina** [comment]
The merge didn't go well, and I'm having a hard time tracking down the commits that changed `Discovery.hh`.

I think most of the commits here have already been ported forward in https://github.com/ignitionrobotics/ign-transport/pull/136/, but they were squashed so I can't tell for sure.

I'll try a new merge.

**Comment by chapulina** [comment]
Ok, I fixed the merge, I think this should be good now. :crossed_fingers: for CI

**Comment by caguero** [comment]
Looks good but I think we should wait until `Focal CI` is happy. Waiting on #159 to be ready and merged.

**Comment by ahcorde** [comment]
I see this error in Focal

```
 /github/workspace/src/Node.cc:623:49: error: 'class zmq::socket_t' has no member named 'set'; did you mean 'send'?
       this->dataPtr->shared->dataPtr->subscriber->set(
                                                   ^~~
                                                   send
  /github/workspace/src/Node.cc:624:12: error: 'zmq::sockopt' has not been declared
         zmq::sockopt::unsubscribe, fullyQualifiedTopic);
              ^~~~~~~
```

Not sure but but we should change these line:
```
#if (CPPZMQ_VERSION >= 40700)
```
for:
```
#if (CPPZMQ_VERSION > 40700)
```

**Comment by chapulina** [comment]
> I see this error in Focal

See https://github.com/ignitionrobotics/ign-transport/pull/159

**Comment by nkoenig** [comment]
I got the same merge as you.

**Review by caguero — APPROVED** [review]

**Comment by nkoenig** [comment]
I think this is good. `Ubuntu CI / Ubuntu Bionic CI (push)` failed to connect to codecov.io.

**Comment by nkoenig** [comment]
I'm going to merge and then make a PR for the next release.

**Pull request merged**
