### PR TITLE
Update deps for Dome: use msgs6

### PR DESCRIPTION
**Pull request by j-rivero**
As part of the works of https://github.com/ignition-tooling/gazebodistro/pull/5 bump the use of msgs to major version 6

### CODE REVIEW

**Comment by caguero** [comment]
Should we also remove `bitbucket-pipelines`?

**Comment by j-rivero** [comment]
> How about updating `.gitbug/workflows/ci-bionic.yaml`? Otherwise I think CI will break.

I would like to avoid the duplication of build-from-source dependencies (we already do that in release-tools) since it adds a good amount of overhead to manage changes in all the repositories, at least until we have a common solution in place. We can discuss this within the project, it is a structural problem of having CI code in many different places.

> Should we also remove `bitbucket-pipelines`?

We are still using it to determine the platform to build branches. That functionality needs to be migrated first.

**Comment by chapulina** [comment]
Pending CI fixes:

* Windows is looking for branch `ign-mshs6` when it should be `master`.
* Ubuntu on Jenkins: I just merged https://github.com/ignition-tooling/release-tools/pull/239, which should fix it.
* OSX: I broke off only the `ign-transport` changes into https://github.com/osrf/homebrew-simulation/pull/1065
* Ubuntu on Actions: @j-rivero said he was going to open a PR adding nightlies to the action

**Comment by j-rivero** [comment]
Github actions are reporting green although [it is a false positive](
https://github.com/ignitionrobotics/ign-transport/pull/149/checks?check_run_id=881935176), related to https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/11.

In order to make it work properly with nightlies we need https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/12 and change this repo to use `gzdev_project_name`.

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by caguero** [comment]
> All Jenkins CI is passing. OSX has 1 test failure and OSX / Windows have warnings. I think we can fix actions later, because all branches will need fixes.
> 
> What do you think, @caguero , can we merge so we can move on with the downstream libs?

Looks good!

**Pull request merged**
